//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C969 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings_es_MX {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings_es_MX() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("C969.strings_es-MX", typeof(strings_es_MX).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Tienes una cita en los próximos 15 minutos!.
        /// </summary>
        internal static string APPOINTMENT {
            get {
                return ResourceManager.GetString("APPOINTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso.
        /// </summary>
        internal static string LOGIN {
            get {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario o contraseña incorrecta.
        /// </summary>
        internal static string LOGINFALSE {
            get {
                return ResourceManager.GetString("LOGINFALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectado.
        /// </summary>
        internal static string LOGINTRUE {
            get {
                return ResourceManager.GetString("LOGINTRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introducir la contraseña.
        /// </summary>
        internal static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro.
        /// </summary>
        internal static string REGISTER {
            get {
                return ResourceManager.GetString("REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombre de usuario ya existe.
        /// </summary>
        internal static string REGISTERFALSE {
            get {
                return ResourceManager.GetString("REGISTERFALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario creado.
        /// </summary>
        internal static string REGISTERTRUE {
            get {
                return ResourceManager.GetString("REGISTERTRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca su nombre de usuario.
        /// </summary>
        internal static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
    }
}
